# Copyright MagnoLabs 2020
# Cloud Build Pipeline

steps:
    - id: 'Upload Files to Storage'
    name: gcr.io/cloud-builders/gsutil
    args: ['-m','cp', '-r', 'stagging/public/*', 'gs://basketball-pro-ui']
  
  - id: 'Set Public on Storage'
    name: gcr.io/cloud-builders/gsutil
    args: ['-m','acl','-r','ch','-u','AllUsers:R', 'gs://basketball-pro-ui/*'] 
