# Copyright MagnoLabs 2020
# Cloud Build Pipeline

steps:
  
    # Install node packages
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]

# Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'build', '--prod' ]
  
  - id: 'Prepare deployment GKE'
    name: 'launcher.gcr.io/google/ubuntu16_04'
    args: ['ls', '-ltr']

  - id: 'Upload Files to Storage'
    name: gcr.io/cloud-builders/gsutil
    args: ['-m','cp', '-r', 'dist/basketball-pro-ui/*', 'gs://basketball-pro-ui']
  
  - id: 'Set Public on Storage'
    name: gcr.io/cloud-builders/gsutil
    args: ['-m','acl','-r','ch','-u','AllUsers:R', 'gs://basketball-pro-ui/*'] 
